# 18개 준공서류 정의
DOCUMENTS = [
    {"id": "doc01", "num": "1",  "name": "준공계",                      "required": True,  "condition": ""},
    {"id": "doc02", "num": "2",  "name": "하도급 공종별 작업내역서",      "required": True,  "condition": "품목·단가·수량·금액 포함"},
    {"id": "doc03", "num": "3",  "name": "시공감리필증",                  "required": True,  "condition": ""},
    {"id": "doc04", "num": "4",  "name": "자재 하역 체크리스트",          "required": True,  "condition": "소규모·관로공사 대상"},
    {"id": "doc05", "num": "4",  "name": "화재위험작업허가서",            "required": False, "condition": "중압/PLP 공사 대상"},
    {"id": "doc06", "num": "5",  "name": "저심도배관현황",                "required": False, "condition": "매설심도 0.6m 미만"},
    {"id": "doc07", "num": "6",  "name": "기밀/내압 시험 데이터",         "required": True,  "condition": ""},
    {"id": "doc08", "num": "8",  "name": "하자보수보증서",                "required": False, "condition": "공사비 500만원 이상(VAT포함)"},
    {"id": "doc09", "num": "9",  "name": "건설기계대여대금지급보증서",    "required": False, "condition": "갱신시"},
    {"id": "doc10", "num": "10", "name": "교육일지/작업일보/스케치",      "required": True,  "condition": ""},
    {"id": "doc11", "num": "11", "name": "융착데이터",                    "required": False, "condition": ""},
    {"id": "doc12", "num": "12", "name": "자재검수보고서",                "required": True,  "condition": ""},
    {"id": "doc13", "num": "13", "name": "산업안전보건관리비 사용내역서", "required": True,  "condition": ""},
    {"id": "doc14", "num": "14", "name": "건설폐기물 인계내역서",         "required": True,  "condition": ""},
    {"id": "doc15", "num": "15", "name": "현장설계변경통보서(FCN)",       "required": False, "condition": "설계변경 시"},
    {"id": "doc16", "num": "16", "name": "개인보호구 지급대장",           "required": False, "condition": "SHE계획서 제출 대상"},
    {"id": "doc17", "num": "17", "name": "일일 현장점검표",               "required": False, "condition": "SHE계획서 제출 대상"},
    {"id": "doc18", "num": "18", "name": "기타서류",                      "required": False, "condition": ""},
]
