[server]
headless = true
enableCORS = false

[theme]
base = "light"
primaryColor = "#5e6ad2"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f7f7f9"
textColor = "#1a1a1a"
font = "sans serif"

[browser]
gatherUsageStats = false
